/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasupermercado.visao;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import sistemasupermercado.dominio.ItemVenda;
import sistemasupermercado.dominio.PrecoProduto;
import sistemasupermercado.dominio.Produto;
import sistemasupermercado.dominio.SessaoCaixa;
import sistemasupermercado.dominio.Venda;
import sistemasupermercado.servicos.ItemVendaServico;
import sistemasupermercado.servicos.PrecoProdutoServico;
import sistemasupermercado.servicos.ProdutoServico;
import sistemasupermercado.servicos.VendaServico;
import sistemasupermercado.visao.tabulacao.IndexedFocusTraversalPolicy;

/**
 *
 * @author Monique
 */
public class FormVenda extends javax.swing.JFrame {

    Venda venda;
    Produto produto;
    PrecoProduto precoProduto;
    List<PrecoProduto> precos;
    SessaoCaixa sessaoCaixa;
    
    BigDecimal total = new BigDecimal(BigInteger.ZERO);
    int quantidadeItens = 0;
    
    VendaServico vendaServico;
    ItemVendaServico itemVendaServico;
    
    
    AtalhoAction acaoEnter = new AtalhoAction("ENTER");
    AtalhoAction acaoF1 = new AtalhoAction("F1");
    AtalhoAction acaoF2 = new AtalhoAction("F2");
    AtalhoAction acaoF3 = new AtalhoAction("F3");
    AtalhoAction acaoF4 = new AtalhoAction("F4");
    AtalhoAction acaoF5 = new AtalhoAction("F5");
    /**
     * Creates new form FormVenda
     */
    private FormVenda() {
        super();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public FormVenda(SessaoCaixa sessaoCaixa) {
        super();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.sessaoCaixa = sessaoCaixa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCaixa = new javax.swing.JLabel();
        lblOpCaixa = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblQuantidadeItens = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtFormaVenda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("F1 - Cancelar item selecionado");
        jPanel2.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("F2 - Cancelar venda");
        jPanel2.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("F3 - Pagamento");
        jPanel2.add(jLabel17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("F4 - Listar produtos");
        jPanel2.add(jLabel18);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("F5 - Sair");
        jPanel2.add(jLabel23);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/ÍconeSair.png"))); // NOI18N
        jLabel11.setText("Sair");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hora:");

        lblData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setText("data");

        lblHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("hora");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Caixa:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Op. Caixa:");

        lblCaixa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCaixa.setForeground(new java.awt.Color(255, 255, 255));
        lblCaixa.setText("número");

        lblOpCaixa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblOpCaixa.setForeground(new java.awt.Color(255, 255, 255));
        lblOpCaixa.setText("op. caixa");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Início:");

        lblInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("inicio");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Unidade:");

        lblUnidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUnidade.setForeground(new java.awt.Color(255, 255, 255));
        lblUnidade.setText("unidade");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora)))
                .addGap(190, 190, 190)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOpCaixa)
                    .addComponent(lblInicio))
                .addGap(173, 173, 173)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnidade)
                    .addComponent(lblCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(lblOpCaixa)
                                .addComponent(jLabel13)
                                .addComponent(lblCaixa))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(lblData)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblHora)
                            .addComponent(jLabel19)
                            .addComponent(lblInicio)
                            .addComponent(jLabel21)
                            .addComponent(lblUnidade)))
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITENS DA VENDA");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        tblItens.setAutoCreateRowSorter(true);
        tblItens.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblItensKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblItens);

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VALOR TOTAL");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("R$ 0,00");
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addContainerGap())
        );

        lblQuantidadeItens.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQuantidadeItens.setForeground(new java.awt.Color(255, 51, 51));
        lblQuantidadeItens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidadeItens.setText("QUANTIDADE DE ITENS: 0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("QUANTIDADE:");

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtQuantidade.setForeground(new java.awt.Color(51, 51, 51));
        txtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusLost(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("PRODUTO:");

        txtProduto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtProduto.setForeground(new java.awt.Color(51, 51, 51));
        txtProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        txtProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProdutoFocusLost(evt);
            }
        });
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProdutoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProdutoKeyTyped(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALHES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtValor.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("VALOR (UN / KG): R$");

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(51, 51, 51));
        txtDescricao.setLineWrap(true);
        txtDescricao.setRows(5);
        jScrollPane2.setViewportView(txtDescricao);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("DESCRIÇÃO:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("CATEGORIA:");

        txtCategoria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(51, 51, 51));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 153, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("FORMA DE VENDA:");

        txtFormaVenda.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtFormaVenda.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCategoria)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(txtValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFormaVenda, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblQuantidadeItens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(lblQuantidadeItens)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtProduto.requestFocus();
        definirDataEHora();
        definirCaixa();
        definirOrdemDeTabulacao();
        definirModeloDeTabela();
        registrarAcoesDosAtalhos();
        
    }//GEN-LAST:event_formWindowOpened

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void tblItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblItensKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()){
            case (KeyEvent.VK_ENTER):
                txtProduto.requestFocus();
                break;
            case (KeyEvent.VK_TAB):
                txtProduto.requestFocus();
                break;
            case (KeyEvent.VK_F1):
                cancelarItem();
                break;
            case (KeyEvent.VK_F2):
                cancelarVenda();
                break;
            case (KeyEvent.VK_F3):
                registrarPagamento();
                break;
            case (KeyEvent.VK_F4):
                listarProdutos();
                break;
            case (KeyEvent.VK_F5):
                sair();
        }
    }//GEN-LAST:event_tblItensKeyPressed

    private void txtProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txtProduto.getText().equals(""))
            pesquisarProduto();
    }//GEN-LAST:event_txtProdutoKeyPressed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && produto != null)
            adicionarItemAVenda();
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void txtProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar() + "")){
            evt.consume();
        }
    }//GEN-LAST:event_txtProdutoKeyTyped

    private void txtProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProdutoFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtProdutoFocusLost

    private void txtQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormVenda dialog = new FormVenda();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCaixa;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblOpCaixa;
    private javax.swing.JLabel lblQuantidadeItens;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtFormaVenda;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    
    private void adicionarItemAVenda() {
        if (txtQuantidade.getText().equals("")) txtQuantidade.setText("1");
        if (venda == null) inserirNovaVenda();
        
        ItemVenda itemVenda = new ItemVenda();
        itemVenda.setNumeroItem(venda.getItens().size() + 1);
        itemVenda.setProduto(produto);
        itemVenda.setVenda(venda);
        itemVenda.setQuantidade(new BigDecimal(txtQuantidade.getText().replaceAll(",", ".")));
        
        BigDecimal subtotal = itemVenda.getQuantidade().multiply(precoProduto.getValor());
        itemVenda.setSubtotal(subtotal);
        
        try {
            
            for (ItemVenda itemColecao : venda.getItens()) {
                if (itemColecao.getProduto().equals(produto) && !itemColecao.isCancelado()){
                    
                    BigDecimal quantidade = itemVenda.getQuantidade().add(itemColecao.getQuantidade());
                    itemVenda.setQuantidade(quantidade);
                    
                    BigDecimal novoSubtotal = subtotal.add(itemColecao.getSubtotal());
                    itemVenda.setSubtotal(novoSubtotal);
                    
                    itemVenda.setNumeroItem(itemColecao.getNumeroItem());
                    
                    itemVendaServico.alterar(itemVenda);
                    
                    itemColecao.setQuantidade(quantidade);
                    itemColecao.setSubtotal(novoSubtotal);
                    
                    alterarItemTabela(itemColecao);
                    atualizarTotal(subtotal);
                    redefinir();
                    return;
                }
            }
            
            itemVendaServico.inserir(itemVenda);
            venda.getItens().add(itemVenda);
            precos.add(precoProduto);

            adicionarItemATabela(itemVenda);
            atualizarTotal(subtotal);
            
            quantidadeItens++;
            lblQuantidadeItens.setText("QUANTIDADE DE ITENS: " + quantidadeItens);
            redefinir();
        } catch(RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(), 
                       "Atenção", JOptionPane.WARNING_MESSAGE);
            redefinir();
        }
        
    }
    
    private void cancelarItem() {
        if (tblItens.getSelectedRowCount() == 0) return;
        for (ItemVenda item : venda.getItens()) {
            int numeroItem = Integer.parseInt(tblItens.getValueAt(tblItens.getSelectedRow(), 0).toString());
            if (item.getNumeroItem() == numeroItem) {
                item.setCancelado(true);
                itemVendaServico.alterar(item);
                tblItens.setValueAt("Sim", tblItens.getSelectedRow(), 6);
                atualizarTotal(new BigDecimal(tblItens.getValueAt(tblItens.getSelectedRow(), 5).toString().replaceAll(",", ".")).negate());
            }
        }
    }
    
    private void cancelarVenda() {
        if (venda == null) return;
        
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar a venda?", "Atenção", 
                    JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.NO_OPTION) return;
        
        try {
            vendaServico.cancelar(venda);
            redefinirVenda();
        } catch(RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(), 
                       "Atenção", JOptionPane.WARNING_MESSAGE);
            redefinir();
        }
    }
    
    private void redefinirVenda() {
        redefinir();
        venda = null;
        limparTabela();
        precos = null;
        total = BigDecimal.ZERO;
        quantidadeItens = 0;
        lblQuantidadeItens.setText("QUANTIDADE DE ITENS: 0 ");
        lblTotal.setText("R$ 0,00");
    }
    
    private void sair() {
        cancelarVenda();
        dispose();
    }
    
    private void redefinir() {
        precoProduto = null;
        produto = null;
        txtProduto.setText("");
        txtQuantidade.setText("");
        txtDescricao.setText("");
        txtValor.setText("");
        txtFormaVenda.setText("");
        txtCategoria.setText("");
        txtProduto.requestFocus();
    }
    
    private void alterarItemTabela(ItemVenda itemVenda) {
        for (int i = 0; i < tblItens.getRowCount(); i++){
            if (itemVenda.getNumeroItem() == Integer.parseInt(tblItens.getValueAt(i, 0).toString())){
                tblItens.setValueAt(itemVenda.getQuantidade().toString().replaceAll("\\.", ","), i, 4);
                tblItens.setValueAt(itemVenda.getSubtotal().toString().replaceAll("\\.", ","), i, 5);
                break;
            }
        }
    }
    
    private void adicionarItemATabela(ItemVenda itemVenda) {
        DefaultTableModel dtm = (DefaultTableModel) tblItens.getModel();
        dtm.addRow(new Object[]{""});
        tblItens.setValueAt(itemVenda.getNumeroItem(), tblItens.getRowCount() - 1, 0);
        tblItens.setValueAt(itemVenda.getProduto().getDescricaoReduzida(), tblItens.getRowCount() - 1, 1);
        tblItens.setValueAt(itemVenda.getProduto().getCodigoDeBarras(), tblItens.getRowCount() - 1, 2);
        tblItens.setValueAt(precoProduto.getValor().toString().replaceAll("\\.", ","), tblItens.getRowCount() -1, 3);
        tblItens.setValueAt(itemVenda.getQuantidade().toString().replaceAll("\\.", ","), tblItens.getRowCount() - 1, 4);
        tblItens.setValueAt(itemVenda.getSubtotal().toString().replaceAll("\\.", ","), tblItens.getRowCount() - 1, 5);
        tblItens.setValueAt("Não", tblItens.getRowCount() - 1, 6);
    }
    
    private void inserirNovaVenda() {
        venda = new Venda();
        vendaServico = new VendaServico();
        venda.setSessao(sessaoCaixa.getSessao());
        try {
            venda = vendaServico.inserir(venda);
            precos = new ArrayList<>();
            venda.setItens(new ArrayList<>());
            
            itemVendaServico = new ItemVendaServico();
            vendaServico = new VendaServico();
        } catch(RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(), 
                        "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    
    private void pesquisarProduto() {
        produto = new Produto();
        ProdutoServico produtoServico = new ProdutoServico();
        
        //Código provisório
        produto.setIdProduto(Integer.parseInt(txtProduto.getText()));
        
        try {
            produto = produtoServico.pesquisar(produto);

            if (produto == null) {
                JOptionPane.showMessageDialog(this, "Produto inexistente!", "Atenção", JOptionPane.WARNING_MESSAGE);
                txtProduto.requestFocus();
                return;
            }

            precoProduto = new PrecoProduto();
            precoProduto.setProduto(produto);
            precoProduto.setUnidade(sessaoCaixa.getSessao().getUsuario().getUnidade());
            precoProduto = new PrecoProdutoServico().pesquisarPrecoAtual(precoProduto);
            if (precoProduto == null) {
                JOptionPane.showMessageDialog(this, "O preço do produto selecionado ainda não foi definido!"
                        + "\nO produto não pode ser vendido.", "Atenção", JOptionPane.WARNING_MESSAGE);
                redefinir();
                //txtProduto.requestFocus();
            } else { 
                txtValor.setText(precoProduto.getValor().toString());
                txtDescricao.setText(produto.getDescricao());
                if (produto.isVendaFracionada()) txtFormaVenda.setText("KG");
                else txtFormaVenda.setText("UN");
                txtCategoria.setText(produto.getCategoria().getDescricao());
                txtQuantidade.requestFocus();
            }
        } catch(RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(), 
                        "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void atualizarTotal(BigDecimal subtotal) {
        total = total.add(subtotal);
        lblTotal.setText("R$ " + total.toString().replaceAll("\\.", ","));
    }
    
    private void registrarPagamento() {
        FormPagamento formPagamento = new FormPagamento(this, true, venda, total);
        formPagamento.setVisible(true);
        redefinirVenda();
    }
    
    private void definirModeloDeTabela() {
        tblItens.setModel(  
            new DefaultTableModel(
                    new Object[] []{ },
                    new String[]{"Item", "Descrição", "Código de barras", "Valor (UN / KG)", "Quantidade", 
                        "Subtotal (R$)", "Cancelado"}
            ) {
                @Override
                public boolean isCellEditable(int row, int col) {  
                        return false;  
                }
            }
        ); 
        
        tblItens.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblItens.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblItens.getColumnModel().getColumn(2).setPreferredWidth(90);
        tblItens.getColumnModel().getColumn(3).setPreferredWidth(90);
        tblItens.getColumnModel().getColumn(4).setPreferredWidth(90);
        tblItens.getColumnModel().getColumn(5).setPreferredWidth(90);
        tblItens.getColumnModel().getColumn(6).setPreferredWidth(60);
        tblItens.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void limparTabela() {
        DefaultTableModel dtm = (DefaultTableModel) tblItens.getModel();
        dtm.setRowCount(0);
    }
    
    private void definirOrdemDeTabulacao() {
        IndexedFocusTraversalPolicy policy = new IndexedFocusTraversalPolicy();
        policy.addIndexedComponent(txtProduto);
        policy.addIndexedComponent(txtQuantidade);
        policy.addIndexedComponent(tblItens);
        setFocusTraversalPolicy(policy);
    }
    
    private void listarProdutos() {
        FormListaProdutos form = new FormListaProdutos(this, true);
        form.setVisible(true);
        if (form.getObjetoSelecionado() != null) {
            txtProduto.setText(form.getObjetoSelecionado().getIdProduto().toString());
            txtQuantidade.requestFocus();
            pesquisarProduto();
        }
    }
        
    private void definirDataEHora() {
        Timer timer = new Timer();
        
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                lblData.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
                lblHora.setText(new SimpleDateFormat("HH:mm:ss").format(new Date(System.currentTimeMillis())));
            }
        };
        
        timer.schedule(task, 1000, 1000);
    }

    private void definirCaixa() {
        lblCaixa.setText(sessaoCaixa.getCaixa().getNumeroCaixa() + "");
        lblOpCaixa.setText(sessaoCaixa.getSessao().getUsuario().getNome());
        lblInicio.setText(new SimpleDateFormat("HH:mm:ss").format(new Date(sessaoCaixa.getSessao().getInicioSessao().getTimeInMillis())));
        lblUnidade.setText(sessaoCaixa.getSessao().getUsuario().getUnidade().getDescricao());
        
    }

    private void registrarAcoesDosAtalhos() {
        ActionMap actionMapForm = this.rootPane.getActionMap();
        actionMapForm.put("acaoEnter", acaoEnter);
        actionMapForm.put("acaoF1", acaoF1);
        actionMapForm.put("acaoF2", acaoF2);
        actionMapForm.put("acaoF3", acaoF3);
        actionMapForm.put("acaoF4", acaoF4);
        actionMapForm.put("acaoF5", acaoF5);
        rootPane.setActionMap(actionMapForm);
        
        InputMap imapForm = this.rootPane.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW);
        imapForm.put(KeyStroke.getKeyStroke("ENTER"), "acaoEnter");
        imapForm.put(KeyStroke.getKeyStroke("F1"), "acaoF1");
        imapForm.put(KeyStroke.getKeyStroke("F2"), "acaoF2");
        imapForm.put(KeyStroke.getKeyStroke("F3"), "acaoF3");
        imapForm.put(KeyStroke.getKeyStroke("F4"), "acaoF4");
        imapForm.put(KeyStroke.getKeyStroke("F5"), "acaoF5");
    }

    
    
    /**
     * Classe usada para criar as ações dos atalhos do teclado (F1, F2 e F3)
     */
    private class AtalhoAction extends AbstractAction {
	private String atalho;

	public AtalhoAction(String atalho)
	{
		super(atalho);
		this.atalho = atalho;
	}
        
        @Override
        public void actionPerformed(ActionEvent ae) {
            switch (atalho){
                case ("ENTER"):
                    //txtProduto.requestFocus();
                    break;
                case ("F1"):
                    cancelarItem();
                    break;
                case ("F2"):
                    cancelarVenda();
                    break;
                case ("F3"):
                    registrarPagamento();
                    break;
                case ("F4"):
                    listarProdutos();
                case ("F5"):
                    sair();
            }
        }

    }
}
