/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasupermercado.visao;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.MathContext;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import sistemasupermercado.dominio.PagamentoVenda;
import sistemasupermercado.dominio.Venda;
import sistemasupermercado.servicos.PagamentoServico;
import sistemasupermercado.servicos.VendaServico;
import sistemasupermercado.visao.tabulacao.IndexedFocusTraversalPolicy;

/**
 *
 * @author Monique
 */
public class FormPagamento extends javax.swing.JDialog {

    PagamentoVenda pagamentoVenda;
    Venda venda;
    
    BigDecimal valorTotal = BigDecimal.ZERO;
    BigDecimal valorAPagar = BigDecimal.ZERO;
    BigDecimal troco = BigDecimal.ZERO;
    
    AtalhoAction acaoF2 = new AtalhoAction("F2");
    AtalhoAction acaoF3 = new AtalhoAction("F3");
    /**
     * Creates new form FormPagamento
     */
    private FormPagamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public FormPagamento(java.awt.Frame parent, boolean modal, Venda venda, BigDecimal total) {
        super(parent, modal);
        initComponents();
        this.venda = venda;
        this.valorTotal = total;
        this.valorAPagar = total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblValorAPagar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        txtDebito = new javax.swing.JTextField();
        txtCredito = new javax.swing.JTextField();
        txtCheque = new javax.swing.JTextField();
        txtVoucher = new javax.swing.JTextField();
        txtOutros = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lblTroco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("F2 - Confirmar pagamento");
        jPanel2.add(jLabel16);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("F3 - Cancelar");
        jPanel2.add(jLabel18);

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VALOR TOTAL");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("R$ 0,00");
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        jPanel7.setForeground(new java.awt.Color(0, 102, 0));

        lblValorAPagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblValorAPagar.setForeground(new java.awt.Color(255, 255, 255));
        lblValorAPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorAPagar.setText("VALOR A PAGAR: R$ 0,00");
        lblValorAPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblValorAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValorAPagar)
                .addGap(39, 39, 39))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formas de Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Dinheiro: R$");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Débito: R$");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Crédito: R$");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Cheque: R$");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Voucher: R$");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Outros: R$");

        txtDinheiro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDinheiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDinheiroFocusLost(evt);
            }
        });
        txtDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDinheiroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDinheiroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDinheiroKeyTyped(evt);
            }
        });

        txtDebito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDebito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDebitoFocusLost(evt);
            }
        });
        txtDebito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDebitoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDebitoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDebitoKeyTyped(evt);
            }
        });

        txtCredito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCredito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCreditoFocusLost(evt);
            }
        });
        txtCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCreditoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCreditoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreditoKeyTyped(evt);
            }
        });

        txtCheque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCheque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtChequeFocusLost(evt);
            }
        });
        txtCheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChequeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChequeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChequeKeyTyped(evt);
            }
        });

        txtVoucher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVoucher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVoucherFocusLost(evt);
            }
        });
        txtVoucher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVoucherKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVoucherKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVoucherKeyTyped(evt);
            }
        });

        txtOutros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOutros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutrosFocusLost(evt);
            }
        });
        txtOutros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOutrosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOutrosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOutrosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDinheiro)
                    .addComponent(txtDebito)
                    .addComponent(txtCredito)
                    .addComponent(txtCheque)
                    .addComponent(txtOutros)
                    .addComponent(txtVoucher))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(102, 204, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        jPanel8.setForeground(new java.awt.Color(0, 102, 0));

        lblTroco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTroco.setForeground(new java.awt.Color(255, 255, 255));
        lblTroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTroco.setText("TROCO: R$ 0,00");
        lblTroco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTroco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDinheiroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtDebito.requestFocus();
            atualizarTotal();
        }
    }//GEN-LAST:event_txtDinheiroKeyPressed

    private void txtDinheiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDinheiroFocusLost
        // TODO add your handling code here:
        //atualizarTotal();
    }//GEN-LAST:event_txtDinheiroFocusLost

    private void txtDebitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDebitoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtCredito.requestFocus();
            atualizarTotal();
        }
    }//GEN-LAST:event_txtDebitoKeyPressed

    private void txtCreditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtCheque.requestFocus();
            atualizarTotal();
        }
    }//GEN-LAST:event_txtCreditoKeyPressed

    private void txtChequeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChequeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtVoucher.requestFocus();
            atualizarTotal();
        }
    }//GEN-LAST:event_txtChequeKeyPressed

    private void txtVoucherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVoucherKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtOutros.requestFocus();
            atualizarTotal();
        }
    }//GEN-LAST:event_txtVoucherKeyPressed

    private void txtOutrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutrosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtDinheiro.requestFocus();
            atualizarTotal();
        }
    }//GEN-LAST:event_txtOutrosKeyPressed

    private void txtDinheiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDinheiroKeyTyped
        // TODO add your handling code here:
        verificarCaracteres(evt);
    }//GEN-LAST:event_txtDinheiroKeyTyped

    private void txtDebitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDebitoKeyTyped
        // TODO add your handling code here:
        verificarCaracteres(evt);
    }//GEN-LAST:event_txtDebitoKeyTyped

    private void txtCreditoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditoKeyTyped
        // TODO add your handling code here:
        verificarCaracteres(evt);
    }//GEN-LAST:event_txtCreditoKeyTyped

    private void txtChequeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChequeKeyTyped
        // TODO add your handling code here:
        verificarCaracteres(evt);
    }//GEN-LAST:event_txtChequeKeyTyped

    private void txtVoucherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVoucherKeyTyped
        // TODO add your handling code here:
        verificarCaracteres(evt);
    }//GEN-LAST:event_txtVoucherKeyTyped

    private void txtOutrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutrosKeyTyped
        // TODO add your handling code here:
        verificarCaracteres(evt);
    }//GEN-LAST:event_txtOutrosKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        registrarAcoesDosAtalhos();
        definirOrdemDeTabulacao();
        lblTotal.setText("R$ " + this.valorTotal.toString().replaceAll("\\.", ","));
    }//GEN-LAST:event_formWindowOpened

    private void txtDebitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDebitoFocusLost
        //atualizarTotal();
    }//GEN-LAST:event_txtDebitoFocusLost

    private void txtCreditoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCreditoFocusLost
        //TODO add your handling code here:
        //atualizarTotal();
    }//GEN-LAST:event_txtCreditoFocusLost

    private void txtChequeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChequeFocusLost
        // TODO add your handling code here:
        //atualizarTotal();
    }//GEN-LAST:event_txtChequeFocusLost

    private void txtVoucherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVoucherFocusLost
        // TODO add your handling code here:
        //atualizarTotal();
    }//GEN-LAST:event_txtVoucherFocusLost

    private void txtOutrosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutrosFocusLost
        // TODO add your handling code here:
        //atualizarTotal();
    }//GEN-LAST:event_txtOutrosFocusLost

    private void txtDinheiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDinheiroKeyReleased
        // TODO add your handling code here:
        atualizarTotal();
    }//GEN-LAST:event_txtDinheiroKeyReleased

    private void txtDebitoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDebitoKeyReleased
        // TODO add your handling code here:
        atualizarTotal();
    }//GEN-LAST:event_txtDebitoKeyReleased

    private void txtCreditoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditoKeyReleased
        // TODO add your handling code here:
        atualizarTotal();
    }//GEN-LAST:event_txtCreditoKeyReleased

    private void txtChequeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChequeKeyReleased
        // TODO add your handling code here:
        atualizarTotal();
    }//GEN-LAST:event_txtChequeKeyReleased

    private void txtVoucherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVoucherKeyReleased
        // TODO add your handling code here:
        atualizarTotal();
    }//GEN-LAST:event_txtVoucherKeyReleased

    private void txtOutrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutrosKeyReleased
        // TODO add your handling code here:
        atualizarTotal();
    }//GEN-LAST:event_txtOutrosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPagamento dialog = new FormPagamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValorAPagar;
    private javax.swing.JTextField txtCheque;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtDebito;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextField txtOutros;
    private javax.swing.JTextField txtVoucher;
    // End of variables declaration//GEN-END:variables

    private void confirmarPagamento() {
        if (troco.compareTo(new BigDecimal(txtDinheiro.getText().replaceAll(",", "."))) >= 0) {
            JOptionPane.showMessageDialog(this, "O valor do troco deve ser menor que o valor pago em dinheiro!\n", 
                        "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            pagamentoVenda = new PagamentoVenda();
            PagamentoServico pagamentoServico = new PagamentoServico();

            pagamentoVenda.setVenda(venda);
            pagamentoVenda.setTroco(troco);
            if (!txtDinheiro.getText().equals("")) pagamentoVenda.setDinheiro(new BigDecimal(txtDinheiro.getText().replaceAll(",", ".")));
            if (!txtDebito.getText().equals("")) pagamentoVenda.setDebito(new BigDecimal(txtDebito.getText().replaceAll(",", ".")));
            if (!txtCredito.getText().equals("")) pagamentoVenda.setCredito(new BigDecimal(txtCredito.getText().replaceAll(",", ".")));
            if (!txtCheque.getText().equals("")) pagamentoVenda.setCheque(new BigDecimal(txtCheque.getText().replaceAll(",", ".")));
            if (!txtVoucher.getText().equals("")) pagamentoVenda.setVoucher(new BigDecimal(txtVoucher.getText().replaceAll(",", ".")));
            if (!txtOutros.getText().equals("")) pagamentoVenda.setOutros(new BigDecimal(txtOutros.getText().replaceAll(",", ".")));

            try {
                VendaServico vendaServico = new VendaServico();
                vendaServico.finalizarVenda(venda);
                pagamentoServico.inserir(pagamentoVenda);
                JOptionPane.showMessageDialog(this, "Venda finalizada com sucesso!", "Finalização de venda", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch(RuntimeException ex) {
                JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(), 
                            "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }
    
    private void cancelarVenda() {
        
        
    }
    
    private void atualizarTotal() {
        valorAPagar = valorTotal;
        
        
        if (!txtDinheiro.getText().equals(""))
            valorAPagar = valorAPagar.subtract(new BigDecimal(txtDinheiro.getText().replaceAll(",", ".")));
        
        if (!txtDebito.getText().equals(""))
            valorAPagar = valorAPagar.subtract(new BigDecimal(txtDebito.getText().replaceAll(",", ".")));
        
        if (!txtCredito.getText().equals(""))
            valorAPagar = valorAPagar.subtract(new BigDecimal(txtCredito.getText().replaceAll(",", ".")));
        
        if (!txtCheque.getText().equals(""))
            valorAPagar = valorAPagar.subtract(new BigDecimal(txtCheque.getText().replaceAll(",", ".")));
        
        if (!txtVoucher.getText().equals(""))
            valorAPagar = valorAPagar.subtract(new BigDecimal(txtVoucher.getText().replaceAll(",", ".")));
        
        if (!txtOutros.getText().equals(""))
            valorAPagar = valorAPagar.subtract(new BigDecimal(txtOutros.getText().replaceAll(",", ".")));
        
        
        
        if (valorAPagar.compareTo(BigDecimal.ZERO) <= 0){
            lblValorAPagar.setText("VALOR A PAGAR: R$ 0,00");
            troco = valorAPagar.abs();
            lblTroco.setText("TROCO: R$ " + troco.toString().replaceAll("\\.", ","));
        } else {
            lblValorAPagar.setText("VALOR A PAGAR: R$ " + valorAPagar.toString().replaceAll("\\.", ","));
            troco = BigDecimal.ZERO;
            lblTroco.setText("TROCO: R$ 0,00");
        }
    }
    
    private void verificarCaracteres(KeyEvent evt) {
        String caracteres="0987654321,";
        if(!caracteres.contains(evt.getKeyChar() + "")){
            evt.consume();
        }
    }
    
    private void definirOrdemDeTabulacao() {
        IndexedFocusTraversalPolicy policy = new IndexedFocusTraversalPolicy();
        policy.addIndexedComponent(txtDinheiro);
        policy.addIndexedComponent(txtDebito);
        policy.addIndexedComponent(txtCredito);
        policy.addIndexedComponent(txtCheque);
        policy.addIndexedComponent(txtVoucher);
        policy.addIndexedComponent(txtOutros);
        setFocusTraversalPolicy(policy);
    }
    
    private void registrarAcoesDosAtalhos() {
        ActionMap actionMapForm = this.rootPane.getActionMap();
        actionMapForm.put("acaof2", acaoF2);
        actionMapForm.put("acaof3", acaoF3);
        rootPane.setActionMap(actionMapForm);
        
        InputMap imapForm = this.rootPane.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW);
        imapForm.put(KeyStroke.getKeyStroke("F2"), "acaof2");
        imapForm.put(KeyStroke.getKeyStroke("F3"), "acaof3");
    }

    /**
     * Classe usada para criar as ações dos atalhos do teclado (F1, F2 e F3)
     */
    private class AtalhoAction extends AbstractAction {
	private String atalho;

	public AtalhoAction(String atalho)
	{
		super(atalho);
		this.atalho = atalho;
	}
        
        @Override
        public void actionPerformed(ActionEvent ae) {
            switch(atalho) {
                case ("F2"):
                    confirmarPagamento();
                    break;
                case ("F3"):
                    cancelarVenda();
            }
        }
    }
}
