
package sistemasupermercado.visao;

import javax.swing.JOptionPane;
import sistemasupermercado.dominio.MotivoProdutoRetirado;
import sistemasupermercado.exceptions.CampoRequeridoVazioException;
import sistemasupermercado.exceptions.PesquisaNulaException;
import sistemasupermercado.servicos.MotivoProdutoRetiradoServico;

public class FormCadastroMotivoProdutoRetirado extends javax.swing.JDialog {
    MotivoProdutoRetirado motivoProdutoRetirado;
    MotivoProdutoRetiradoServico motivoProdutoRetiradoServico;
    /**
     * Creates new form FormCadastroMotivoProdutoRetirado
     */
    public FormCadastroMotivoProdutoRetirado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        redefinir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Motivos de Retirada de Produtos");
        setIconImage(null);
        setIconImages(null);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Motivos de Retirada de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel2.setText("Descrição:");

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        jLabel1.setText("ID:");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/ÍconePesquisar.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/ÍconeEditar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/ÍconeInserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/ÍconeNovo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/ÍconeExcluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 284, Short.MAX_VALUE)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnInserir)
                    .addComponent(btnNovo)
                    .addComponent(btnExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        redefinir();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        motivoProdutoRetirado = new MotivoProdutoRetirado();
        motivoProdutoRetiradoServico = new MotivoProdutoRetiradoServico();
        
        motivoProdutoRetirado.setDescricao(txtDescricao.getText());
        
        try {
            if (motivoProdutoRetiradoServico.inserir(motivoProdutoRetirado)) {
                int resposta = JOptionPane.showConfirmDialog(this, "Cadastro realizado com sucesso. \nDeseja permanecer"
                        + "no cadastro de motivos?", "Confirmação de Cadastro", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) { redefinir(); }
                else { dispose(); }
            } else {
                JOptionPane.showMessageDialog(this, "Ocorreu uma falha não especificada ao tentar inserir o motivo.", 
                        "Não foi possível concluir o cadastro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (CampoRequeridoVazioException ex) {
            JOptionPane.showMessageDialog(this, "Preencha o(s) campo(s) necessário(s) para continuar. \n" + ex.getMessage(), 
                        "Campo(s) obrigatório(s) vazio(s)", JOptionPane.INFORMATION_MESSAGE);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha ao tentar inserir o motivo: \n" + ex.getMessage(), 
                        "Não foi possível concluir o cadastro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        motivoProdutoRetirado = new MotivoProdutoRetirado();
        motivoProdutoRetiradoServico = new MotivoProdutoRetiradoServico();
        
        if (txtId.getText().equals("")) return; // <<< Código provisório 
        
        motivoProdutoRetirado.setIdMotivo(Integer.parseInt(txtId.getText()));
        try {
            motivoProdutoRetirado = motivoProdutoRetiradoServico.pesquisar(motivoProdutoRetirado);
            txtDescricao.setText(motivoProdutoRetirado.getDescricao());
            
            txtId.setEditable(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnInserir.setEnabled(false);
            btnPesquisar.setEnabled(false);
            
        } catch (PesquisaNulaException ex) {
            JOptionPane.showMessageDialog(this, "A pesquisa não retornou nenhum resultado. \n" + ex.getMessage(), 
                        "Pesquisa sem resultado", JOptionPane.INFORMATION_MESSAGE);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a pesquisa. \n" + ex.getMessage(), 
                        "Não foi possível realizar a pesquisa", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        //motivoProdutoRetirado = new MotivoProdutoRetirado();
        //motivoProdutoRetiradoServico = new MotivoProdutoRetiradoServico();
        
        //motivoProdutoRetirado.setIdMotivo(Integer.parseInt(txtId.getText()));
        motivoProdutoRetirado.setDescricao(txtDescricao.getText());
        
        try {
            if (motivoProdutoRetiradoServico.alterar(motivoProdutoRetirado)) {
                int resposta = JOptionPane.showConfirmDialog(this, "Alteração realizada com sucesso. \nDeseja permanecer"
                        + "no cadastro de motivos?", "Confirmação de alteração", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) { redefinir(); }
                else { dispose(); }
            } else {
                JOptionPane.showMessageDialog(this, "Ocorreu uma falha não especificada ao tentar alterar o motivo.", 
                        "Não foi possível concluir a alteração", JOptionPane.ERROR_MESSAGE);
            }
        } catch (CampoRequeridoVazioException ex) {
            JOptionPane.showMessageDialog(this, "Preencha o(s) campo(s) necessário(s) para continuar. \n" + ex.getMessage(), 
                        "Campo(s) obrigatório(s) vazio(s)", JOptionPane.INFORMATION_MESSAGE);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha ao tentar alterar o motivo: \n" + ex.getMessage(), 
                        "Não foi possível concluir a alteração", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //motivoProdutoRetirado = new MotivoProdutoRetirado();
        //motivoProdutoRetiradoServico = new MotivoProdutoRetiradoServico();
        
        //motivoProdutoRetirado.setIdMotivo(Integer.parseInt(txtId.getText()));
        
        try {
            if (motivoProdutoRetiradoServico.excluir(motivoProdutoRetirado)) {
                int resposta = JOptionPane.showConfirmDialog(this, "Exclusão realizada com sucesso. \nDeseja permanecer"
                        + "no cadastro de motivos?", "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) { redefinir(); }
                else { dispose(); }
            } else {
                JOptionPane.showMessageDialog(this, "Ocorreu uma falha não especificada ao tentar excluir o motivo.", 
                        "Não foi possível concluir a exclusao", JOptionPane.ERROR_MESSAGE);
            }
        } catch (CampoRequeridoVazioException ex) {
            JOptionPane.showMessageDialog(this, "Preencha o(s) campo(s) necessário(s) para continuar. \n" + ex.getMessage(), 
                        "Campo(s) obrigatório(s) vazio(s)", JOptionPane.INFORMATION_MESSAGE);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha ao tentar realizar a excliusão: \n" + ex.getMessage(), 
                        "Não foi possível concluir a exclusão", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        
    }//GEN-LAST:event_txtIdKeyPressed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    
    
    private void redefinir() {
        txtId.setText("");
        txtDescricao.setText("");
        txtId.requestFocus();
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnInserir.setEnabled(true);
        txtId.setEditable(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroMotivoProdutoRetirado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroMotivoProdutoRetirado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroMotivoProdutoRetirado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroMotivoProdutoRetirado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCadastroMotivoProdutoRetirado dialog = new FormCadastroMotivoProdutoRetirado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
