/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasupermercado.visao;

import java.awt.event.ActionEvent;
import java.math.BigDecimal;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import sistemasupermercado.dominio.MotivoProdutoRetirado;
import sistemasupermercado.dominio.Produto;
import sistemasupermercado.dominio.ProdutoRetirado;
import sistemasupermercado.dominio.Sessao;
import sistemasupermercado.servicos.MotivoProdutoRetiradoServico;
import sistemasupermercado.servicos.ProdutoRetiradoServico;
import sistemasupermercado.servicos.ProdutoServico;
import sistemasupermercado.visao.tabulacao.IndexedFocusTraversalPolicy;

/**
 *
 * @author Monique
 */
public class FormRegistroProdutoRetirado extends javax.swing.JDialog {

    Sessao sessao;
    
    ProdutoRetirado produtoRetirado;
    Produto produto;
    
    ProdutoRetiradoServico produtoRetiradoServico;
    ProdutoServico produtoServico;
    
    AtalhoAction acaoF1 = new AtalhoAction("F1");
    AtalhoAction acaoF2 = new AtalhoAction("F2");
    AtalhoAction acaoF3 = new AtalhoAction("F3");
    AtalhoAction acaoF4 = new AtalhoAction("F4");
    AtalhoAction acaoF5 = new AtalhoAction("F5");
    
    /**
     * Creates new form FormProdutoRetirado
     */
    private FormRegistroProdutoRetirado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public FormRegistroProdutoRetirado(java.awt.Frame parent, boolean modal, Sessao sessao) {
        super(parent, modal);
        this.sessao = sessao;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblCodigoDeBarras = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblDescricaoReduzida = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        btnPesquisarProduto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblFormaDeVenda = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JFormattedTextField();
        btnNovo = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbMotivo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos Retirados");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Produtos Retirados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 153, 255))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel8.setText("ID Produto:");

        txtIdProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdProdutoFocusLost(evt);
            }
        });
        txtIdProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdProdutoKeyTyped(evt);
            }
        });

        jLabel9.setText("Código de barras:");

        lblCodigoDeBarras.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Descrição:");

        lblDescricao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Descrição reduzida:");

        lblDescricaoReduzida.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Categoria:");

        lblCategoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/ÍconePesquisar.png"))); // NOI18N
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Forma de venda:");

        lblFormaDeVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCodigoDeBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricaoReduzida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFormaDeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(lblCodigoDeBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblDescricaoReduzida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblFormaDeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Quantidade:");

        txtQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/ÍconeNovoMenor.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/ÍconeGravarMenor.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGravar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Motivo:");

        jLabel4.setText("Observação:");

        txtObservacao.setColumns(20);
        txtObservacao.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidade)
                            .addComponent(cmbMotivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGravar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("F1 - Pesquisa produto");
        jPanel5.add(jLabel20);

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("F2 - Lista produtos");
        jPanel5.add(jLabel24);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("F3 - Novo");
        jPanel5.add(jLabel22);

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("F4 - Grava registro");
        jPanel5.add(jLabel23);

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("F5 - Lista motivos");
        jPanel5.add(jLabel25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        if (produto == null || txtQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "É necessário preencher todos os campos para continuar.",
                "Pesquisa sem resultado", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        produtoRetirado = new ProdutoRetirado();
        produtoRetiradoServico = new ProdutoRetiradoServico();

        produtoRetirado.setProduto(produto);
        produtoRetirado.setSessao(sessao);
        produtoRetirado.setMotivo((MotivoProdutoRetirado) cmbMotivo.getSelectedItem());
        produtoRetirado.setQuantidade(new BigDecimal(txtQuantidade.getText().replaceAll(",", ".")));
        produtoRetirado.setObservacao(txtObservacao.getText());

        try {
            produtoRetiradoServico.inserir(produtoRetirado);

            int resposta = JOptionPane.showConfirmDialog(this, "Retirada de produtos registrada com sucesso!\n"
                + "Deseja continuar no registro de saída"
                    + " de produtos?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) redefinir();
            else dispose();
        } catch(RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(),
                "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        redefinir();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321,";
        if(!caracteres.contains(evt.getKeyChar() + "")){
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantidadeKeyTyped

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        if (txtIdProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "É necessário inserir o ID para pesquisar.",
                "Pesquisa sem resultado", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        produto = new Produto();
        produtoServico = new ProdutoServico();
        produto.setIdProduto(Integer.parseInt(txtIdProduto.getText()));

        try {
            produto = produtoServico.pesquisarProdutoEstocavel(produto);
            lblDescricao.setText(produto.getDescricao());
            lblDescricaoReduzida.setText(produto.getDescricaoReduzida());
            lblCodigoDeBarras.setText(produto.getCodigoDeBarras());
            lblCategoria.setText(produto.getCategoria().getDescricao());

            if (produto.isVendaFracionada()) lblFormaDeVenda.setText("KG");
            else lblFormaDeVenda.setText("UN");

            txtQuantidade.requestFocus();
        } catch(RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(),
                "Atenção", JOptionPane.WARNING_MESSAGE);
            redefinirProduto();
        }
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void txtIdProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProdutoKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar() + "")){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdProdutoKeyTyped

    private void txtIdProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdProdutoFocusLost
        // TODO add your handling code here:
        if (txtIdProduto.getText().equals("")) {
            return;
        }

        produto = new Produto();
        produtoServico = new ProdutoServico();
        produto.setIdProduto(Integer.parseInt(txtIdProduto.getText()));

        try {
            produto = produtoServico.pesquisarProdutoEstocavel(produto);
            lblDescricao.setText(produto.getDescricao());
            lblDescricaoReduzida.setText(produto.getDescricaoReduzida());
            lblCodigoDeBarras.setText(produto.getCodigoDeBarras());
            lblCategoria.setText(produto.getCategoria().getDescricao());

            if (produto.isVendaFracionada()) lblFormaDeVenda.setText("KG");
            else lblFormaDeVenda.setText("UN");
        } catch(RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "O ID do produto informado não é válido.\n" + ex.getMessage(),
                "Atenção", JOptionPane.INFORMATION_MESSAGE);
            redefinirProduto();
        }
    }//GEN-LAST:event_txtIdProdutoFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        registrarAcoesDosAtalhos();
        definirOrdemDeTabulação();
        preencherCmbMotivos();
        redefinir();
        
        // Código provisório
        /*sessao = new Sessao();
        sessao.setIdSessao(1);
        sessao.setUsuario(1);
        sessao.getUsuario().setUnidade(1);*/
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistroProdutoRetirado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistroProdutoRetirado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistroProdutoRetirado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistroProdutoRetirado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormRegistroProdutoRetirado dialog = new FormRegistroProdutoRetirado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JComboBox cmbMotivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigoDeBarras;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricaoReduzida;
    private javax.swing.JLabel lblFormaDeVenda;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JFormattedTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

    private void redefinir() {
        redefinirProduto();
        
        txtQuantidade.setText("");
        txtObservacao.setText("");
        
        txtIdProduto.requestFocus();
    }
    
    private void redefinirProduto() {
        txtIdProduto.setText("");
        lblCategoria.setText("");
        lblCodigoDeBarras.setText("");
        lblDescricao.setText("");
        lblDescricaoReduzida.setText("");
        lblFormaDeVenda.setText("");
        produto = null;
    }
    
    private void exibirListaProdutos() {
        FormListaProdutos form = new FormListaProdutos(null, true);
        form.setVisible(true);
        if (form.getObjetoSelecionado() != null) {
            txtIdProduto.setText(form.getObjetoSelecionado().getIdProduto().toString());
            btnPesquisarProdutoActionPerformed(null);
        }
    }
    
    private void exibirListaMotivos() {
        FormListaMotivoProdutoRetirado form = new FormListaMotivoProdutoRetirado(null, true);
        form.setVisible(true);
        MotivoProdutoRetirado motivo = form.getObjetoSelecionado();
        if (motivo != null) {
            for (int i = 0; i < cmbMotivo.getItemCount(); i++){
                MotivoProdutoRetirado motivoItem = (MotivoProdutoRetirado) cmbMotivo.getItemAt(i);
                if (motivoItem.getIdMotivo().equals(motivo.getIdMotivo())) {
                    cmbMotivo.setSelectedItem(motivoItem);
                    break;
                }
            }
        }
    }

    private void preencherCmbMotivos() {
        MotivoProdutoRetiradoServico m = new MotivoProdutoRetiradoServico();
        try {
            DefaultComboBoxModel<MotivoProdutoRetirado> model = new DefaultComboBoxModel<>(new Vector<>(m.listar()));
            cmbMotivo.setModel(model);
        } catch(RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(),
                    "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void registrarAcoesDosAtalhos() {
        ActionMap actionMapForm = this.rootPane.getActionMap();
        actionMapForm.put("acaof1", acaoF1);
        actionMapForm.put("acaof2", acaoF2);
        actionMapForm.put("acaof3", acaoF3);
        actionMapForm.put("acaof4", acaoF4);
        actionMapForm.put("acaof5", acaoF5);
        rootPane.setActionMap(actionMapForm);
        
        InputMap imapForm = this.rootPane.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW);
        imapForm.put(KeyStroke.getKeyStroke("F1"), "acaof1");
        imapForm.put(KeyStroke.getKeyStroke("F2"), "acaof2");
        imapForm.put(KeyStroke.getKeyStroke("F3"), "acaof3");
        imapForm.put(KeyStroke.getKeyStroke("F4"), "acaof4");
        imapForm.put(KeyStroke.getKeyStroke("F5"), "acaof5");
    }

    private void definirOrdemDeTabulação() {
        IndexedFocusTraversalPolicy policy = new IndexedFocusTraversalPolicy();
        policy.addIndexedComponent(txtIdProduto);
        policy.addIndexedComponent(txtQuantidade);
        policy.addIndexedComponent(cmbMotivo);
        setFocusTraversalPolicy(policy);
    }
    
    /**
     * Classe usada para criar as ações dos atalhos do teclado (F1, F2 e F3)
     */
    private class AtalhoAction extends AbstractAction {
	private String atalho;

	public AtalhoAction(String atalho)
	{
		super(atalho);
		this.atalho = atalho;
	}
        
        @Override
        public void actionPerformed(ActionEvent ae) {
            switch(atalho) {
                case ("F1"):
                    btnPesquisarProdutoActionPerformed(ae);
                    break;
                case ("F2"):
                    exibirListaProdutos();
                    break;
                case ("F3"):
                    btnNovoActionPerformed(ae);
                    break;
                case ("F4"):
                    btnGravarActionPerformed(ae);
                    break;
                case ("F5"):
                    exibirListaMotivos();
            }
        }

    }
}
