/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasupermercado.visao;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import sistemasupermercado.dominio.Sessao;
import sistemasupermercado.dominio.SessaoCaixa;
import sistemasupermercado.relatorios.GeradorDeRelatorioDeFornecedores;
import sistemasupermercado.relatorios.GeradorDeRelatorioDeProdutosRetirados;
import sistemasupermercado.relatorios.GeradorDeRelatorios;
import sistemasupermercado.servicos.SessaoCaixaServico;
import sistemasupermercado.servicos.SessaoServico;
import sistemasupermercado.visao.imagepanel.JImagePanel;
/**
 *
 * @author Monique
 */
public class FormMenuPrincipal extends javax.swing.JFrame {

    Sessao sessao; 
    
    SessaoCaixa sessaoCaixa;
    /**
     * Creates new form FormMenuPrincipal
     */
    private FormMenuPrincipal() {
        definirImagemDeFundo();
        initComponents();
        
        
    }
    
    public FormMenuPrincipal(Sessao sessao) {
        this.sessao = sessao;
        definirImagemDeFundo();
        initComponents();
        
    }
    
    

    private void definirImagemDeFundo() {
        try {
            JImagePanel panel = new JImagePanel(
                    //loadImage(this.getClass().getResource("/sistemasupermercado/imagens/background.png").getFile()));
                    loadImage("C:\\Program Files\\MarketSoft\\SistemaSupermercado\\src\\sistemasupermercado\\imagens\\background.png"));
//panel.setFillType(JImagePanel.FillType.CENTER);
            this.setContentPane(panel);
            //this.pack();
        } catch (IOException ex) {
            Logger.getLogger(FormMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private static BufferedImage loadImage(String file) throws IOException {
        return ImageIO.read(new File(file));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        lblFuncao = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVenda = new javax.swing.JMenu();
        jMenuItemIniciarCaixa = new javax.swing.JMenuItem();
        jMenuItemRealizarVenda = new javax.swing.JMenuItem();
        jMenuItemFinalizarCaixa = new javax.swing.JMenuItem();
        jMenuCaixas = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItemCadastroDeCaixas = new javax.swing.JMenuItem();
        jMenuEstoque = new javax.swing.JMenu();
        jMenuItemRegistrarEntradaProdutos = new javax.swing.JMenuItem();
        jMenuItemRegistrarSaídaProdutos = new javax.swing.JMenuItem();
        jMenuItemConsultaEstoque = new javax.swing.JMenuItem();
        jMenuItemConsultaDeEntradasDeProdutos = new javax.swing.JMenuItem();
        jMenuItemConsultaDeProdutosRetirados = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroProdutos = new javax.swing.JMenuItem();
        jMenuItemCadastroPrecos = new javax.swing.JMenuItem();
        jMenuItemCadastroFornecedores = new javax.swing.JMenuItem();
        jMenuItemCadastroCategorias = new javax.swing.JMenuItem();
        jMenuItemCadastroMotivos = new javax.swing.JMenuItem();
        jMenuItemCadastroUsuarios = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuItemConsultaUsuarios = new javax.swing.JMenuItem();
        jMenuItemConsultaFornecedores = new javax.swing.JMenuItem();
        jMenuItemConsultaProdutos = new javax.swing.JMenuItem();
        jMenuItemConsultaVendas = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemEncerrarSessao = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Marketsoft");
        setExtendedState(6);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/sistemasupermercado/imagens/icone.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasupermercado/imagens/logotipo.png"))); // NOI18N

        lblHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("Hora:");

        lblData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblData.setText("Data:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Usuário:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Unidade:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Função:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Início:");

        lblUnidade.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblUnidade.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidade.setText("dados");

        lblFuncao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblFuncao.setForeground(new java.awt.Color(102, 102, 102));
        lblFuncao.setText("dados");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(102, 102, 102));
        lblUsuario.setText("dados");

        lblInicio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(102, 102, 102));
        lblInicio.setText("dados");

        jMenuVenda.setText("Venda");

        jMenuItemIniciarCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemIniciarCaixa.setText("Abrir Caixa");
        jMenuItemIniciarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIniciarCaixaActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemIniciarCaixa);

        jMenuItemRealizarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRealizarVenda.setText("Realizar Venda");
        jMenuItemRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRealizarVendaActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemRealizarVenda);

        jMenuItemFinalizarCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFinalizarCaixa.setText("Fechar Caixa");
        jMenuItemFinalizarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinalizarCaixaActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemFinalizarCaixa);

        jMenuBar1.add(jMenuVenda);

        jMenuCaixas.setText("Caixas");

        jMenuItem4.setText("Observar Caixas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuCaixas.add(jMenuItem4);

        jMenuItemCadastroDeCaixas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadastroDeCaixas.setText("Adicionar Caixas");
        jMenuItemCadastroDeCaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeCaixasActionPerformed(evt);
            }
        });
        jMenuCaixas.add(jMenuItemCadastroDeCaixas);

        jMenuBar1.add(jMenuCaixas);

        jMenuEstoque.setText("Estoque");

        jMenuItemRegistrarEntradaProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRegistrarEntradaProdutos.setText("Registrar Entrada de Produtos");
        jMenuItemRegistrarEntradaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarEntradaProdutosActionPerformed(evt);
            }
        });
        jMenuEstoque.add(jMenuItemRegistrarEntradaProdutos);

        jMenuItemRegistrarSaídaProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRegistrarSaídaProdutos.setText("Registrar Saída de Produtos");
        jMenuItemRegistrarSaídaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarSaídaProdutosActionPerformed(evt);
            }
        });
        jMenuEstoque.add(jMenuItemRegistrarSaídaProdutos);

        jMenuItemConsultaEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemConsultaEstoque.setText("Consulta de Estoque");
        jMenuItemConsultaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaEstoqueActionPerformed(evt);
            }
        });
        jMenuEstoque.add(jMenuItemConsultaEstoque);

        jMenuItemConsultaDeEntradasDeProdutos.setText("Consulta de Entradas de Produtos");
        jMenuItemConsultaDeEntradasDeProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaDeEntradasDeProdutosActionPerformed(evt);
            }
        });
        jMenuEstoque.add(jMenuItemConsultaDeEntradasDeProdutos);

        jMenuItemConsultaDeProdutosRetirados.setText("Consulta de Produtos Retirados de Estoque");
        jMenuItemConsultaDeProdutosRetirados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaDeProdutosRetiradosActionPerformed(evt);
            }
        });
        jMenuEstoque.add(jMenuItemConsultaDeProdutosRetirados);

        jMenuBar1.add(jMenuEstoque);

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroProdutos.setText("Cadastro de Produtos");
        jMenuItemCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroProdutos);

        jMenuItemCadastroPrecos.setText("Cadastro de Preços");
        jMenuItemCadastroPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroPrecosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroPrecos);

        jMenuItemCadastroFornecedores.setText("Cadastro de Fornecedores");
        jMenuItemCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroFornecedoresActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroFornecedores);

        jMenuItemCadastroCategorias.setText("Cadastro de Categorias de Produtos");
        jMenuItemCadastroCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroCategoriasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroCategorias);

        jMenuItemCadastroMotivos.setText("Cadastro de Motivos Retirada de Produtos");
        jMenuItemCadastroMotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroMotivosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroMotivos);

        jMenuItemCadastroUsuarios.setText("Cadastro de Usuários");
        jMenuItemCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroUsuarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuConsulta.setText("Consulta");

        jMenuItemConsultaUsuarios.setText("Consulta de Usuários");
        jMenuItemConsultaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaUsuariosActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaUsuarios);

        jMenuItemConsultaFornecedores.setText("Consulta de Fornecedores");
        jMenuItemConsultaFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaFornecedoresActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaFornecedores);

        jMenuItemConsultaProdutos.setText("Consulta de Produtos e Preços");
        jMenuItemConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaProdutosActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaProdutos);

        jMenuItemConsultaVendas.setText("Consulta de Vendas");
        jMenuItemConsultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaVendasActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaVendas);

        jMenuBar1.add(jMenuConsulta);

        jMenuRelatorios.setText("Relatórios");

        jMenuItem1.setText("Gerar Relatório de Fornecedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem1);

        jMenuItem5.setText("Gerar Relatório de Produtos Vendidos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem5);

        jMenuItem17.setText("Gerar Relatório de Saída de Produtos");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem17);

        jMenuItem2.setText("Gerar Relatório de Vendas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem2);

        jMenuItem6.setText("Gerar Relatório de Usuários");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem6);

        jMenuBar1.add(jMenuRelatorios);

        jMenuSair.setText("Sair");

        jMenuItemEncerrarSessao.setText("Encerrar Sessão");
        jMenuItemEncerrarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEncerrarSessaoActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemEncerrarSessao);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(lblUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidade)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFuncao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblInicio))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRealizarVendaActionPerformed
        // TODO add your handling code here:
        if (sessaoCaixa == null) {
            JOptionPane.showMessageDialog(this, "É necessário abrir o caixa para realizar vendas!", "Caixa aberto", 
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            FormVenda formVenda = new FormVenda(sessaoCaixa);
            formVenda.setVisible(true);
        }
        
    }//GEN-LAST:event_jMenuItemRealizarVendaActionPerformed

    private void jMenuItemRegistrarSaídaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarSaídaProdutosActionPerformed
        // TODO add your handling code here:
        FormRegistroProdutoRetirado formRegistroProdutoRetirado = new FormRegistroProdutoRetirado(this, true, sessao);
        formRegistroProdutoRetirado.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarSaídaProdutosActionPerformed

    private void jMenuItemRegistrarEntradaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarEntradaProdutosActionPerformed
        // TODO add your handling code here:
        FormRegistroEntradaProduto formRegistroEntradaProduto = new FormRegistroEntradaProduto(this, true, sessao);
        formRegistroEntradaProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarEntradaProdutosActionPerformed

    private void jMenuItemCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutosActionPerformed
        // TODO add your handling code here:
        FormCadastroProduto formCadastroProduto = new FormCadastroProduto(this, true);
        formCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroProdutosActionPerformed

    private void jMenuItemCadastroPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroPrecosActionPerformed
        // TODO add your handling code here:
        //Provisório
        
        FormCadastroPrecoProduto formCadastroPrecoProduto = new FormCadastroPrecoProduto(this, true, sessao.getUsuario().getUnidade());
        
        formCadastroPrecoProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroPrecosActionPerformed

    private void jMenuItemCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroFornecedoresActionPerformed
        // TODO add your handling code here:
        FormCadastroFornecedor formCadastroFornecedor = new FormCadastroFornecedor(this, true);
        formCadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroFornecedoresActionPerformed

    private void jMenuItemCadastroCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroCategoriasActionPerformed
        // TODO add your handling code here:
        FormCadastroCategoriaProduto formCadastroCategoriaProduto = new FormCadastroCategoriaProduto(this, rootPaneCheckingEnabled);
        formCadastroCategoriaProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroCategoriasActionPerformed

    private void jMenuItemCadastroMotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroMotivosActionPerformed
        // TODO add your handling code here:
        FormCadastroMotivoProdutoRetirado formCadastroMotivoProdutoRetirado = new FormCadastroMotivoProdutoRetirado(this, true);
        formCadastroMotivoProdutoRetirado.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroMotivosActionPerformed

    private void jMenuItemCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUsuariosActionPerformed
        // TODO add your handling code here:
        FormCadastroUsuario formCadastroUsuario = new FormCadastroUsuario(this, true, sessao.getUsuario().getUnidade());
        formCadastroUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroUsuariosActionPerformed

    private void jMenuItemConsultaFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaFornecedoresActionPerformed
        // TODO add your handling code here:
        FormConsultaFornecedor formConsultaFornecedor = new FormConsultaFornecedor(this, true);
        formConsultaFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaFornecedoresActionPerformed

    private void jMenuItemConsultaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaUsuariosActionPerformed
        // TODO add your handling code here:
        FormConsultaUsuario formConsultaUsuario = new FormConsultaUsuario(this, true, sessao.getUsuario().getUnidade());
        formConsultaUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaUsuariosActionPerformed

    private void jMenuItemConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaProdutosActionPerformed
        // TODO add your handling code here:
        FormConsultaProdutos formConsultaProdutos = new FormConsultaProdutos(this, true, sessao.getUsuario().getUnidade());
        formConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaProdutosActionPerformed

    private void jMenuItemCadastroDeCaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeCaixasActionPerformed
        // TODO add your handling code here:
        FormCadastroCaixa formCadastroCaixa = new FormCadastroCaixa(this, rootPaneCheckingEnabled, 
                sessao.getUsuario().getUnidade());
        formCadastroCaixa.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroDeCaixasActionPerformed

    private void jMenuItemConsultaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaEstoqueActionPerformed
        // TODO add your handling code here:
        FormConsultaEstoque formConsultaEstoque = new FormConsultaEstoque(this, true, sessao.getUsuario().getUnidade());
        formConsultaEstoque.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaEstoqueActionPerformed

    private void jMenuItemConsultaDeEntradasDeProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaDeEntradasDeProdutosActionPerformed
        // TODO add your handling code here:
        FormConsultaEntradaDeProdutos form = new FormConsultaEntradaDeProdutos(this, true, sessao);
        form.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemConsultaDeEntradasDeProdutosActionPerformed

    private void jMenuItemConsultaDeProdutosRetiradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaDeProdutosRetiradosActionPerformed
        // TODO add your handling code here:
        FormConsultaProdutosRetirados form = new FormConsultaProdutosRetirados(this, true, sessao);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaDeProdutosRetiradosActionPerformed

    private void jMenuItemIniciarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIniciarCaixaActionPerformed
        // TODO add your handling code here:
        if (sessaoCaixa != null)
            JOptionPane.showMessageDialog(this, "O caixa já está aberto!", "Caixa aberto", JOptionPane.INFORMATION_MESSAGE);
        else {
            FormAberturaDeCaixa form = new FormAberturaDeCaixa(this, true, sessao);
            form.setVisible(true);
            sessaoCaixa = form.getSessaoCaixa();
        }
    }//GEN-LAST:event_jMenuItemIniciarCaixaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        definirDataEHora();
        definirUsuario();
        switch (sessao.getUsuario().getFuncaoUsuario().getIdFuncao()){
            case (1):
                verificarCaixaAberto();
                break;
            case (2):
                verificarCaixaAberto();
                jMenuCadastro.setEnabled(false);
                jMenuCaixas.setEnabled(false);
                jMenuConsulta.setEnabled(false);
                jMenuEstoque.setEnabled(false);
                jMenuRelatorios.setEnabled(false);
                break;
            case (3):
                jMenuCaixas.setEnabled(false);
                jMenuVenda.setEnabled(false);
                jMenuItemCadastroUsuarios.setEnabled(false);
                jMenuItemConsultaVendas.setEnabled(false);
                jMenuItemConsultaUsuarios.setEnabled(false);
                jMenuRelatorios.setEnabled(false);
                break;
            default:
                verificarCaixaAberto();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemEncerrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEncerrarSessaoActionPerformed
        // TODO add your handling code here:
        if (sessaoCaixa != null)
            JOptionPane.showMessageDialog(this, "É necessário realizar o fechamento do caixa antes de encerrar a sessão!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
        else {
            SessaoServico sessaoServico = new SessaoServico();
            try {
                sessaoServico.encerrarSessao(sessao);
            System.exit(0);
            } catch(RuntimeException ex) {
                JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(),
                        "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jMenuItemEncerrarSessaoActionPerformed

    private void jMenuItemFinalizarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinalizarCaixaActionPerformed
        // TODO add your handling code here:
        
        if (sessaoCaixa == null){
            JOptionPane.showMessageDialog(this, "O caixa não foi aberto.\n",
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }else {
            FormFechamentoDeCaixa formFechamentoDeCaixa = new FormFechamentoDeCaixa(this, true, sessaoCaixa);
            formFechamentoDeCaixa.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jMenuItemFinalizarCaixaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FormObservarCaixas formObservarCaixas = new FormObservarCaixas(this, true, sessao);
        formObservarCaixas.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemConsultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaVendasActionPerformed
        // TODO add your handling code here:
        FormConsultaVenda formConsultaVenda = new FormConsultaVenda(this, true, sessao.getUsuario().getUnidade());
        formConsultaVenda.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaVendasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        if (sessaoCaixa != null){
            JOptionPane.showMessageDialog(this, "O caixa não foi encerrado.\nÉ necessário fechar o caixa antes de encerrar a sessão!",
                    "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }else{
             int escolha = JOptionPane.showConfirmDialog(this, "Deseja realmente encerrar a sessão?\n",
                    "Atenção", JOptionPane.YES_NO_OPTION);
            if (escolha == JOptionPane.YES_OPTION){
                SessaoServico sessaoServico = new SessaoServico();
                try {
                    sessaoServico.encerrarSessao(sessao);
                    System.exit(0);
                } catch(RuntimeException ex) {
                    JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(),
                            "Atenção", JOptionPane.WARNING_MESSAGE);
                }
            }
        } 
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        FormGeradorDeRelatorioDeProdutosRetirados f = new FormGeradorDeRelatorioDeProdutosRetirados(this, true, sessao);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        GeradorDeRelatorioDeFornecedores f = new GeradorDeRelatorioDeFornecedores();

        try {
            f.abrirRelatorio().setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(FormMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormGeradorDeRelatorioDeVendas form = new FormGeradorDeRelatorioDeVendas(this, true, sessao);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        FormGeradorDeRelatorioDeProdutosVendidos form = new FormGeradorDeRelatorioDeProdutosVendidos(this, true, sessao);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        FormGeradorDeRelatorioDeUsuarios form = new FormGeradorDeRelatorioDeUsuarios(this, true, sessao);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCaixas;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenu jMenuEstoque;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemCadastroCategorias;
    private javax.swing.JMenuItem jMenuItemCadastroDeCaixas;
    private javax.swing.JMenuItem jMenuItemCadastroFornecedores;
    private javax.swing.JMenuItem jMenuItemCadastroMotivos;
    private javax.swing.JMenuItem jMenuItemCadastroPrecos;
    private javax.swing.JMenuItem jMenuItemCadastroProdutos;
    private javax.swing.JMenuItem jMenuItemCadastroUsuarios;
    private javax.swing.JMenuItem jMenuItemConsultaDeEntradasDeProdutos;
    private javax.swing.JMenuItem jMenuItemConsultaDeProdutosRetirados;
    private javax.swing.JMenuItem jMenuItemConsultaEstoque;
    private javax.swing.JMenuItem jMenuItemConsultaFornecedores;
    private javax.swing.JMenuItem jMenuItemConsultaProdutos;
    private javax.swing.JMenuItem jMenuItemConsultaUsuarios;
    private javax.swing.JMenuItem jMenuItemConsultaVendas;
    private javax.swing.JMenuItem jMenuItemEncerrarSessao;
    private javax.swing.JMenuItem jMenuItemFinalizarCaixa;
    private javax.swing.JMenuItem jMenuItemIniciarCaixa;
    private javax.swing.JMenuItem jMenuItemRealizarVenda;
    private javax.swing.JMenuItem jMenuItemRegistrarEntradaProdutos;
    private javax.swing.JMenuItem jMenuItemRegistrarSaídaProdutos;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

    public void verificarCaixaAberto() {
        SessaoCaixaServico sessaoCaixaServico = new SessaoCaixaServico();
            try {
                sessaoCaixa = sessaoCaixaServico.verificarCaixaAberto(sessao);
                if (sessaoCaixa != null) sessaoCaixa.setSessao(sessao);
            } catch(RuntimeException ex) {
                JOptionPane.showMessageDialog(this, "Ocorreu uma falha durante a execução.\n" + ex.getMessage(),
                        "Atenção", JOptionPane.WARNING_MESSAGE);
            }
    }
    
    private void definirDataEHora() {
        Timer timer = new Timer();
        
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                lblData.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
                lblHora.setText(new SimpleDateFormat("HH:mm:ss").format(new Date(System.currentTimeMillis())));
            }
        };
        
        timer.schedule(task, 1000, 1000);
    }
    
    private void definirUsuario() {
        lblFuncao.setText(sessao.getUsuario().getFuncaoUsuario().getDescricao());
        lblUsuario.setText(sessao.getUsuario().getNome());
        lblInicio.setText(new SimpleDateFormat("dd/MM/yyy HH:mm:ss").format(new Date(sessao.getInicioSessao().getTimeInMillis())));
        lblUnidade.setText(sessao.getUsuario().getUnidade().getDescricao());
        
    }
}
